imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@GatotKacaErpMainBundle/Resources/config/services.yml" }
    - { resource: "@GatotKacaErpMainBundle/Resources/config/config.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [GatotKacaErpMainBundle]

# Doctrine Configuration
doctrine:
    dbal:
      connections:
        default:
          driver:   "%database_driver%"
          host:     "%database_host%"
          port:     "%database_port%"
          dbname:   "%database_name%"
          user:     "%database_user%"
          password: "%database_password%"
          charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

# KNP Snappy Bundle
knp_snappy:
    pdf:
        enabled:    true
        binary:     "%kernel.root_dir%/Resources/tools/wkhtmltopdf"
        options:    []
    image:
        enabled:    true
        binary:     "%kernel.root_dir%/Resources/tools/wkhtmltoimage"
        options:    []

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
