doctrine:
  orm:
    entity_managers:
      default:
        auto_mapping: true
        dql:
          datetime_functions:
            TO_CHAR: GatotKaca\Core\Doctrine\DQL\PostgreSQL\DateTime\ToChar
          string_functions:
            SPLIT_PART: GatotKaca\Core\Doctrine\DQL\PostgreSQL\String\SplitPart
