doctrine:
  orm:
    entity_managers:
      default:
        auto_mapping: true
        dql:
          datetime_functions:
            TO_CHAR: GatotKaca\Erp\MainBundle\Doctrine\DQL\PostgreSQL\DateTime\ToChar
          string_functions:
            SPLIT_PART: GatotKaca\Erp\MainBundle\Doctrine\DQL\PostgreSQL\String\SplitPart