services:
  kejawen.helper:
    class: GatotKaca\Erp\MainBundle\Helper\Helper
  kejawen.security:
    class: GatotKaca\Erp\UtilitiesBundle\Model\SecurityModel
    arguments:
      entityManager: "@doctrine.orm.entity_manager"
      helper: "@kejawen.helper"
  kejawen.setting:
    class: GatotKaca\Erp\UtilitiesBundle\Model\SettingModel
    arguments:
      entityManager: "@doctrine.orm.entity_manager"
      helper: "@kejawen.helper"
  kejawen.model.manager:
    class: GatotKaca\Erp\MainBundle\Helper\ModelManager
    arguments:
      entityManager: "@doctrine.orm.entity_manager"
      helper: "@kejawen.helper"
  kejawen.kernel.listener:
    class: GatotKaca\Erp\MainBundle\Listener\GatotKacaEventListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }